<?php
if (!strpos($_SERVER['REQUEST_URI'], 'isFrame')) {
?>
<script type="text/javascript" language="javascript">
<!--//
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?220b1fd78079208854b1033416f6cf05";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();

(function() {var _53code = document.createElement("script");_53code.src = "https://tb.53kf.com/code/code/10176001/1";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(_53code, s);})();
//-->
</script>
<?php
}
?>