    <footer class="row">
      <p class="col-md-9 col-sm-9 col-xs-12 copyright">&copy; gc <?php echo date('Y') ?></p>
      <p class="col-md-3 col-sm-3 col-xs-12 powered-by">Powered by: gc</p>
    </footer>
  </body>
</html>
<script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="js/jquery.cookie.js"></script>

<script src='bower_components/moment/min/moment.min.js'></script>
<script src='bower_components/fullcalendar/dist/fullcalendar.min.js'></script>

<script src='js/jquery.dataTables.min.js'></script>

<script src="bower_components/chosen/chosen.jquery.min.js"></script>

<script src="bower_components/colorbox/jquery.colorbox-min.js"></script>

<script src="js/jquery.noty.js"></script>

<script src="bower_components/responsive-tables/responsive-tables.js"></script>

<script src="bower_components/bootstrap-tour/build/js/bootstrap-tour.min.js"></script>

<script src="js/jquery.raty.min.js"></script>

<script src="js/jquery.iphone.toggle.js"></script>

<script src="js/jquery.autogrow-textarea.js"></script>

<script src="js/jquery.uploadify-3.1.min.js"></script>

<script src="js/jquery.history.js"></script>

<script src="js/charisma.js"></script>