<?php
require_once('init.inc');
require_once('../../ext/vcs.inc');
VCS::start(); 
?>
<!doctype html>
<html>
  <head>
    <script language="javascript" src="../../js/jquery-2.1.4.min.js"></script>
    <script language="javascript" src="../../js/agui.js"></script>
    <script type="text/javascript" src="../../js/vcs.js"></script>
      
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,initial-scale=1.0,user-scalable=no, minimal-ui" />
    <meta name="format-detection" content="telephone=no"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <!-- 强制浏览器清理缓存
    <meta content="no-cache" http-equiv="pragma">
    <meta content="no-cache" http-equiv="cache-control">
    <meta content="0" http-equiv="expires">  
    --> 
    <!-- 手机上电话号码不要默认显示为链接
    <meta name="format-detection" content="telephone=no"/>
    -->